# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-23 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default=b'en_US', max_length=255)),
                ('push_token', models.CharField(max_length=255, null=True)),
                ('platform', models.CharField(choices=[(b'ios', b'iOS'), (b'android', b'Android')], max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('sns_platform_endpoint_arn', models.CharField(max_length=255, null=True, unique=True, verbose_name='SNS Platform Endpoint')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'date_updated',
                'ordering': ('-date_updated',),
                'abstract': False,
                'verbose_name_plural': 'Devices',
                'verbose_name': 'Device',
            },
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('push_token', 'platform')]),
        ),
    ]
