# Generated by Django 2.2.4 on 2020-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_sandbox_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
