# Generated by Django 2.2.4 on 2019-08-09 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from django_sloop.settings import DJANGO_SLOOP_SETTINGS


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(DJANGO_SLOOP_SETTINGS["DEVICE_MODEL"]),
    ]

    operations = [
        migrations.CreateModel(
            name='PushMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('data', models.TextField()),
                ('sns_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sns_response', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_messages', to=DJANGO_SLOOP_SETTINGS["DEVICE_MODEL"])),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
            },
        ),
    ]
