# Generated by Django 2.2.4 on 2019-08-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sloop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushmessage',
            options={'verbose_name': 'Push Message', 'verbose_name_plural': 'Push Messages'},
        ),
    ]
