from django.conf import settings

DJANGO_SLOOP_SETTINGS = getattr(settings, "DJANGO_SLOOP_SETTINGS", {})

# Defaults
DJANGO_SLOOP_SETTINGS.setdefault("AWS_REGION_NAME", None)
DJANGO_SLOOP_SETTINGS.setdefault("AWS_ACCESS_KEY_ID", None)
DJANGO_SLOOP_SETTINGS.setdefault("AWS_SECRET_ACCESS_KEY", None)
DJANGO_SLOOP_SETTINGS.setdefault("SNS_IOS_APPLICATION_ARN", None)
DJANGO_SLOOP_SETTINGS.setdefault("SNS_IOS_SANDBOX_ENABLED", False)
DJANGO_SLOOP_SETTINGS.setdefault("SNS_ANDROID_APPLICATION_ARN", None)
DJANGO_SLOOP_SETTINGS.setdefault("LOG_SENT_MESSAGES", False)
DJANGO_SLOOP_SETTINGS.setdefault("DEFAULT_SOUND", None)
DJANGO_SLOOP_SETTINGS.setdefault("DEVICE_MODEL", None)


if not DJANGO_SLOOP_SETTINGS.get("DEVICE_MODEL"):
    assert False, "DJANGO_SLOOP_SETTINGS: DEVICE_MODEL is required."
